CREATE TABLE IF NOT EXISTS user_intelligence (user_id TEXT PRIMARY KEY, username TEXT, discriminator TEXT, avatar_hash TEXT, account_created TIMESTAMPTZ, risk_score INTEGER DEFAULT 0, risk_level TEXT DEFAULT 'clean', profile_score INTEGER DEFAULT 0, username_score INTEGER DEFAULT 0, behavior_score INTEGER DEFAULT 0, network_score INTEGER DEFAULT 0, is_flagged BOOLEAN DEFAULT FALSE, flag_reason TEXT, total_verifications INTEGER DEFAULT 0, failed_verifications INTEGER DEFAULT 0, guilds_seen TEXT[] DEFAULT '{}', first_seen TIMESTAMPTZ DEFAULT NOW(), last_seen TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ip_records (ip_address TEXT PRIMARY KEY, is_vpn BOOLEAN DEFAULT FALSE, is_proxy BOOLEAN DEFAULT FALSE, is_tor BOOLEAN DEFAULT FALSE, is_datacenter BOOLEAN DEFAULT FALSE, country_code TEXT, region TEXT, asn TEXT, isp TEXT, risk_score INTEGER DEFAULT 0, user_ids TEXT[] DEFAULT '{}', flagged BOOLEAN DEFAULT FALSE, flag_reason TEXT, last_seen TIMESTAMPTZ DEFAULT NOW(), created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS alt_groups (id SERIAL PRIMARY KEY, primary_user_id TEXT NOT NULL, alt_user_id TEXT NOT NULL, confidence INTEGER DEFAULT 0, reason TEXT[] DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(primary_user_id, alt_user_id));
CREATE TABLE IF NOT EXISTS username_patterns (id SERIAL PRIMARY KEY, pattern TEXT NOT NULL, pattern_type TEXT NOT NULL, score_addition INTEGER DEFAULT 10, description TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS behavior_events (id SERIAL PRIMARY KEY, user_id TEXT NOT NULL, guild_id TEXT NOT NULL, event_type TEXT NOT NULL, click_ms INTEGER, metadata JSONB, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS join_patterns (id SERIAL PRIMARY KEY, guild_id TEXT NOT NULL, user_id TEXT NOT NULL, joined_at TIMESTAMPTZ DEFAULT NOW(), account_age_days INTEGER, risk_score INTEGER, was_raid BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS risk_history (id SERIAL PRIMARY KEY, user_id TEXT NOT NULL, old_score INTEGER, new_score INTEGER, reason TEXT, changed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS flagged_accounts (user_id TEXT PRIMARY KEY, reason TEXT NOT NULL, flagged_by TEXT, severity TEXT DEFAULT 'medium', active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW());
INSERT INTO username_patterns (pattern, pattern_type, score_addition, description) VALUES
('[a-z]{2,4}[0-9]{4,8}$','regex',20,'Letters followed by many numbers'),('[a-zA-Z0-9]{16,}','regex',15,'Very long random string'),('(user|member|discord|bot)[0-9]+','regex',25,'Generic bot-like name'), ('([a-z])\\1{3,}','regex',20,'Repeated characters'), ('(deleted|banned|null|undefined)','keyword',30,'Suspicious keywords'), ('[^a-zA-Z0-9_.]','regex',10,'Unusual special characters') ON CONFLICT DO NOTHING;
